<?php
/**
 * Auto generated by prado-cli.php on 2008-03-18 12:28:13.
 */
class BarangRecord extends TActiveRecord
{
	const TABLE='tbm_barang';

	public $id;
	public $nama;
	public $ukuran;
	public $satuan;
	public $st_barang;
	
	public $deleted;
	
	public static function finder($className=__CLASS__)
	{
		return parent::finder($className);
	}
}
?>
